services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todo-task'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  task-service-1:
    build: .
    container_name: task-service-1
    ports:
      - "9082:8082"
    environment:
      - Name=instance1
    depends_on:
      - postgres
  task-service-2:
    build: .
    container_name: task-service-2
    ports:
      - "9083:8082"
    environment:
      - Name=instance2
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - 8082:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - task-service-1
      - task-service-2
