services:
  eureka-server:
    image: eureka-server:latest
    build:
      context: ./
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - server.port=8761
      - spring.datasource.url=jdbc:postgresql://postgres:5432/todo-task
      - spring.datasource.username=postgres
      - spring.datasource.password=root
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todo-task'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672'
  task-service-1:
    build: .
    container_name: task-service-1
    ports:
      - "8083:8083"
    environment:
      - server.port=8083
      - spring.datasource.url=jdbc:postgresql://postgres:5432/todo-task
      - spring.datasource.username=postgres
      - spring.datasource.password=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - Name=instance1
    depends_on:
      - postgres
      - eureka-server


  task-service-2:
    build: .
    container_name: task-service-2
    ports:
      - "8084:8084"
    environment:
      - server.port=8084
      - spring.datasource.url=jdbc:postgresql://postgres:5432/todo-task
      - spring.datasource.username=postgres
      - spring.datasource.password=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - Name=instance2
    depends_on:
      - postgres
      - eureka-server

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - 6436:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - task-service-1
      - task-service-2

