apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: ebramfadl/task-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: spring.datasource.url
              value: jdbc:postgresql://postgres:5432/todo-board
            - name: spring.datasource.username
              value: postgres
            - name: spring.datasource.password
              value: root
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: eureka-server
            - name: spring.rabbitmq.host
              value: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
